name: Update Password
on:
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут
  workflow_dispatch:         # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random password
        id: generate
        run: |
          # Генерируем 3 блока по 4 случайных символа (A-Z, 0-9)
          PART1=$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]' | cut -c1-4)
          PART2=$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]' | cut -c1-4)
          PART3=$(openssl rand -hex 2 | tr '[:lower:]' '[:upper:]' | cut -c1-4)
          NEW_PASS="ART_FT-$PART1-$PART2-$PART3"
          echo "NEW_PASS=$NEW_PASS" >> $GITHUB_OUTPUT

      - name: Update Gist
        env:
          GIST_ID: "71260671daac59f9043b964e6cc83976"  # Замените на ваш Gist ID
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "description": "Auto-updated password (changes every 15 min)",
              "files": {
                "password.txt": {
                  "content": "${{ steps.generate.outputs.NEW_PASS }}"
                }
              }
            }' \
            "https://api.github.com/gists/$GIST_ID"
          echo "✅ Новый пароль: ${{ steps.generate.outputs.NEW_PASS }}"
