name: Update Password
on:
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GIST_ID: "71260671daac59f9043b964e6cc83976"
      GH_TOKEN: ${{ secrets.UPD_TOKEN }}
    steps:
      - name: Setup jq
        run: sudo apt-get install -y jq

      - name: Generate random password
        id: generate
        run: |
          PART1=$(tr -dc A-Z0-9 </dev/urandom | head -c4)
          PART2=$(tr -dc A-Z0-9 </dev/urandom | head -c4)
          PART3=$(tr -dc A-Z0-9 </dev/urandom | head -c4)
          NEW_PASS="ART_FT-$PART1-$PART2-$PART3"
          echo "NEW_PASS=$NEW_PASS" >> $GITHUB_ENV
          echo "Generated: $NEW_PASS"

      - name: Update Gist
        run: |
          JSON_PAYLOAD=$(jq -n \
            --arg desc "Auto-updated password (changes every 15 min)" \
            --arg content "$NEW_PASS" \
            '{description: $desc, files: {"password.txt": {content: $content}}}')

          RESPONSE=$(curl -sS -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            "https://api.github.com/gists/$GIST_ID")

          if echo "$RESPONSE" | grep -q '"updated_at"'; then
            echo "✅ Updated at: $(echo "$RESPONSE" | jq -r '.updated_at')"
          else
            echo "❌ Failed to update gist"
            echo "$RESPONSE"
            exit 1
          fi
