name: Update Password
on:
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random password
        id: generate
        run: |
          # Генерация пароля формата ART_FT-XXXX-XXXX-XXXX
          PART1=$(head /dev/urandom | tr -dc A-Z0-9 | head -c4)
          PART2=$(head /dev/urandom | tr -dc A-Z0-9 | head -c4)
          PART3=$(head /dev/urandom | tr -dc A-Z0-9 | head -c4)
          NEW_PASS="ART_FT-$PART1-$PART2-$PART3"
          echo "NEW_PASS=$NEW_PASS" >> $GITHUB_OUTPUT
          echo "Generated password: $NEW_PASS"

      - name: Update Gist
        env:
          GIST_ID: "71260671daac59f9043b964e6cc83976"
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          # Проверка наличия токена
          if [ -z "$GH_TOKEN" ]; then
            echo "❌ Error: GH_TOKEN is empty!"
            exit 1
          fi

          # Обновление Gist
          echo "Updating gist $GIST_ID..."
          RESPONSE=$(curl -s -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
              "files": {
                "password.txt": {
                  "content": "'"${{ steps.generate.outputs.NEW_PASS }}"'"
                }
              }
            }' \
            "https://api.github.com/gists/$GIST_ID")

          # Проверка результата
          if echo "$RESPONSE" | grep -q '"updated_at"'; then
            echo "✅ Gist updated successfully!"
            echo "New password: ${{ steps.generate.outputs.NEW_PASS }}"
          else
            echo "❌ Failed to update gist:"
            echo "$RESPONSE"
            exit 1
          fi
